### ISSUE TITLE
Jitpack is broken

### ISSUE THREAD

**Issue by lineargraph** [eutro/hierarchical-lang#1]
Jitpack is broken because this doesnt have the `maven` plugin.

**Comment by eutro** [comment]
Jitpack is broken because Loom requires Java 16 while Jitpack builds with Java 8, or something. Either way, Jitpack shouldn't be necessary since this is on the [Gradle plugin portal](https://plugins.gradle.org/plugin/com.github.eutro.hierarchical-lang) (though there are some issues I'm trying to fix right now).

**Comment by eutro** [comment]
Those issues with the plugin portal have hopefully been fixed now.

Please try to use the version from the [Gradle plugin portal](https://plugins.gradle.org/plugin/com.github.eutro.hierarchical-lang) which is much easier than Jitpack, since it's implicitly available for the `plugins` block anyway. I'm not even sure how you would apply a Gradle plugin through Jitpack anyway, you'd have to use legacy plugin application and that just sounds like a world of pain.

The `maven` plugin was deprecated and has been removed, actually, and `maven-publish` [is used instead](https://github.com/eutro/hierarchical-lang/blob/7fcf07f72a2c72b2215e20d9a13e39d0d81b6126/hierarchical-lang-gradle/build.gradle.kts#L9).

**Comment by lineargraph** [comment]
Neat, thanks :)
